### ISSUE TITLE
destroyAll method and duplicated components tag

### ISSUE THREAD

**Issue by gabibianconi** [krakenjs/xcomponent#103]
I'm creating a component as follow:
```javascript
function createNew() {
  window.viewComponent = xcomponent.create({
      tag: 'my-component',
      url: 'http://myurl.com'
  });
}
```
After this, I invoke the render method and works fine.
Later, I want to create a new component with another URL, but previously I want to delete 'my-component', so, I have this: 
```javascript
function myFunction() {
    if (window.viewComponent) {
      xcomponent.destroyAll().then( () => createNew() );
    } else {
      createNew();
    }
}
```
But the following error message is shown when xcomponent create method is invoked:
"Can not register multiple components with the same tag"

I know I can't create two components with the same tag, but I think if I delete the first one previously it shouldn't be problem. Note that 'my-component' is being deleted from the DOM, but it is not being created again after delete it.
Now, I'm using a dynamic tag but I want to know why "destroyAll()" method is not removing all the data. Could this cause an excessive memory consumption in case run the flow mentioned above many times? I ask this because if some data is not being removed...

Thanks

**Comment by bluepnume** [comment]
So, `destroyAll()` actually just means "destroy all rendered instances of components". There isn't actually currently a way to destroy an existing component -- but I would potentially be open to this being added in future.

If all you need to do is change the url, could you do something like this?

```javascript
  window.viewComponent = xcomponent.create({
      tag: 'my-component',
      get url() {
          return someCondition ? 'http://myurl.com' : 'http://myurl2.com';
      }
  });
```

**Comment by gabibianconi** [comment]
Thanks, could be. But, I have n URLs. And sometimes two components at the same time. What do you recommend?

**Comment by bluepnume** [comment]
What do the different urls represent? Different environments, or different experiences?

**Comment by gabibianconi** [comment]
Different domain pages. Like: "http://someurl.com" and "http://otherurl.com"

**Comment by bluepnume** [comment]
Sure -- but what I'm getting at is, are they different apps with different experiences? In which case, would it not be better to register different xcomponents for them?

**Comment by gabibianconi** [comment]
Sure, so, is it better create a new component for each url? I thought about that, but then I have this use case: I need to load a URL in a xcomponent. After that, I need to go to another xcomponent with other URL. And after, come back to the first one. In this case I will not be able to create a new xcompoenent because it will has the same tag that the first one. So I come back to the dynamic tag. I was thinking about how to iterate all the created components and check if already exist a component whit the same tag and in this case only invoke the render method instead create method. It is this possible?

**Comment by bluepnume** [comment]
Sounds like it might be better to have two different xcomponents for this use case.

Can you create the first xcomponent once, and render it multiple times? Like:

```javascript
var SomeComponent = xcomponent.create({ ... });

SomeComponent.render({ ... }, '#container');

// some time later, render the component a second time

SomeComponent.render({ ... }, '#container2');
```

**Comment by gabibianconi** [comment]
Yes, this works for me. Remember you could add the delete method for components in the future or add this feature to destroyAll() method. Thank you so much Daniel.
