### ISSUE TITLE
Popup are not opening with chrome latest version  59.0.3071.115, It's opening in tab.

### ISSUE THREAD

**Issue by NitinWabale** [krakenjs/xcomponent#104]
Older version (before update 59.0.3071.115 ) of chrome, popup was working.

**Comment by harouny** [comment]
For anyone interested, maybe that is related to that issue:
https://superuser.com/questions/1223168/how-can-chrome-59-0-3071-115-be-configured-to-not-open-a-popup-as-a-new-tab

**Comment by bluepnume** [comment]
Which version of xcomponent are you using? I saw a similar issue a week or so back and made a quick fix.

**Comment by NitinWabale** [comment]
we are using xcomponent  "2.0.50". which version you made fix?

**Comment by NitinWabale** [comment]
we are using xcomponent  "2.0.50". which version you made fix?

**Comment by bluepnume** [comment]
The fix is in `2.0.51`.

**Comment by raphaelcosta** [comment]
@bluepnume It's happening with me on `2.0.64`, I am missing something?

**Comment by bluepnume** [comment]
@raphaelcosta what's the exact behavior you see? render() opens a new tab, rather than a popup?

**Comment by raphaelcosta** [comment]
@bluepnume yes

**Comment by bluepnume** [comment]
@raphaelcosta do you see the same issue when you try clicking on the paypal button here: https://developer.paypal.com/demo/checkout/

**Comment by raphaelcosta** [comment]
no, I am using the popup option to true, it's still correct?

**Comment by bluepnume** [comment]
Can you share your full component code?

**Comment by raphaelcosta** [comment]
I have a lot of code behind to create the xcomponent, but it works on Safari.

**Comment by bluepnume** [comment]
OK -- but it would be good to have an idea of the options you're passing to `xcomponent.create`, like `dimensions`, `contexts`, etc.

**Comment by bluepnume** [comment]
Can you confirm?
