### ISSUE TITLE
Set new dimensions without rerender React component

### ISSUE THREAD

**Issue by raphaelcosta** [krakenjs/xcomponent#106]
It's possible to set new Iframe dimensions without react rerender iframe and change URL?

**Comment by bluepnume** [comment]
Yes -- depending on where you are, you should be able to call `resize()`

From the child: `window.xchild.resize(width, height)`

From a prop in the parent: `this.resize(width, height)`

**Comment by raphaelcosta** [comment]
Thanks @bluepnume ! You are amazing

**Comment by ruhusobeje** [comment]
@bluepnume 
Sorry to reopen the issue. I am facing a similar one.

In the xcomponent.create I have:
```
autoResize: {
    height: true,
    width: true
}
```
But it does not autoresize.

I tried  to pass a prop from parent `resizeParent:function(){ window.resize('100%', '100%');}`
Then, calling window.xprops.resizeParent();

I have a react component as child. It is a list of items.
I would like to resize parent container once there are more/less items in the child.

But that did not work as well 😟


Thanks!
