### ISSUE TITLE
iframe 100% width and height

### ISSUE THREAD

**Issue by vigosan** [krakenjs/xcomponent#109]
With the last version of xcomponent, the size of the iframe container is set to`150x300px` by default (https://github.com/krakenjs/xcomponent/blob/4092ef5e33c2340c167fa40c3adf4874f5d60d66/src/component/component/templates/container.jsx). If you give to the iframe a size of `100%x100%`, its size will be `150x300px` as maximum :

![screen shot 2017-07-28 at 12 36 38](https://user-images.githubusercontent.com/767/28714017-bd9e557e-7391-11e7-90fd-ebf715d699f6.png)

```    
Payment: xcomponent.create({
      tag: 'fw-payment',
      dimensions: {
        height: '100%',
        width: '100%'
      },
      url:  'https://some.url',
      autoResize: false,
      scrolling: true
    })
```

Is there a way to overwrite these defaults? Or how can we configure the iframe to be 100%x100%?

**Comment by harouny** [comment]
I also notice that and had to stop migrating to latest version.

**Comment by bluepnume** [comment]
Damn, thanks for the report. Let me take a look at this.

**Comment by bluepnume** [comment]
OK, this should be resolved with the latest version. Please let me know if you still see the problem.

For more advanced / granular control over the dimensions and positioning of the iframe, also feel free to play around with overriding the `containerTemplate`. This is the default: https://github.com/krakenjs/xcomponent/blob/master/src/component/component/templates/container.jsx
