### ISSUE TITLE
Callback when props change inside iframe

### ISSUE THREAD

**Issue by ps-video-player** [krakenjs/xcomponent#111]
I'm passing down state from the iframe to my component using xcomponent. I'm using `updateProps` to then modify the props. These are getting passed down to the component, but I don't know when they change so I can't react to them. Is there a hook on child window to register a callback for when `updateProps` is called from the parent?

**Comment by bluepnume** [comment]
Absolutely, you can do:

```javascript
window.xchild.onProps(props => {
    ...
});
```

**Comment by ps-video-player** [comment]
Just what I was looking for! I might have completely missed it, but is `xchild` documented anywhere? Or is the code the best place to look currently?

**Comment by bluepnume** [comment]
Yeah, it's something I need to get round to documenting. Glad it works for you though!
