### ISSUE TITLE
Disable/Change loading spinner

### ISSUE THREAD

**Issue by richardpeng** [krakenjs/xcomponent#114]
I'm trying to either disable or change the loading spinner but am unsure how to do so. I've tried setting `prerenderTemplate` to `null`, a function returning an empty string, an empty string, but none of those really work. My goal is to continue showing the loading spinner until the Facebook login component has finished autoloading and attempted to login. Right now, the component autoresizes a bunch of times: 
![2017-09-09 14 29 01](https://user-images.githubusercontent.com/430409/30242805-61a3be02-956b-11e7-8ffa-a37b4edf050a.gif)

```
import xcomponent from 'xcomponent';

function prerenderTemplate() {
    return ""
}

window.MyLoginComponent = xcomponent.create({
	tag: 'login-component',
	url: 'http://localhost:8080',
	dimensions: {
	  width: '100%',
		height: '150px'
	},
	autoResize: true,
    prerenderTemplate: prerenderTemplate
});
```

**Comment by bluepnume** [comment]
For now, could you hide the container by default, then have a prop which you call from the child frame when everything is rendered, which displays the container?

**Comment by harouny** [comment]
A bit of general feedback here on ```prerenderTemplate```:
In my experience its much simpler and consistent to relay on the component itself to provide a visual loading indicator in the html file before loading any scripts or more styles. Given that the component is a single page app.

For example:

Given that my component is defined as:
``` javascript
window.MyLoginComponent = xcomponent.create({
	tag: 'login-component',
	url: 'http://localhost:8080/login.html'
});
```
In my ```login.html``` I have:

``` html
<!doctype html>
<html>
<head>
    <style>
    .spinner {
      /* add css animation here. i.e. http://tobiasahlin.com/spinkit/ */
    }
  </style>
<sty
</head>
<body>
  <my-login-angular-or-react-component>
    <div class="spinner"></div>
  </my-login-angular-or-react-component>
  <script src="app.bundle.js"></script>
</body>
</html>
```
Browser will load ```login.html``` in the Iframe very quickly as Its very small in size, the initial spinner UI will be displayed until browser loads rest of app scripts, templates and styles. Spinner UI will go away only when the app is bootstrapped.

In my opinion ```prerenderTemplate``` is only useful if the whole page UI is rendered as part of the initial html file downloaded by the browser i.e. using server side rendering.

**Comment by bluepnume** [comment]
Yeah, absolutely, the content in the iframe should have some kind of loading spinner by default unless it's server-side rendered.

But in both cases - server and client rendered - depending on the network speed of your clients, you're still going to get an empty iframe during the time it takes for that initial request to go through. That's where `prerenderTemplate` becomes useful.

I maybe jumped the gun though, adding a default spinner here. I need to figure out why setting it to `null` didn't disable it though...
