### ISSUE TITLE
Why should child be aware of url?

### ISSUE THREAD

**Issue by AndyOGo** [krakenjs/xcomponent#117]
In my case I have a component which should be internationalised and distributed at language/country-code url paths.

Do I really need to change my components definitions for every single iframe?

Like:

**de**:
````js
window.FooXComponent = xcomponent.create({
  tag: 'foo-x-component',
  url: 'http://www.example.org/de',
````

**en**:
````js
window.FooXComponent = xcomponent.create({
  tag: 'foo-x-component',
  url: 'http://www.example.org/en',
````

> Btw. I'm aware that I could move all i18n related props up to XComponent's `xprops`. Tough I would not prefer to need to change that...

**Comment by bluepnume** [comment]
How do you decide the locale normally? Could you do something with a `language` variable, like:

```javascript
window.FooXComponent = xcomponent.create({
  tag: 'foo-x-component',
  url: 'http://www.example.org/' + language,
```

**Comment by AndyOGo** [comment]
@bluepnume 
Thanks for your quick response.
Good to know regarding query params.

Well I pass a locale like `de-CH` down.
As a interim solution I added a simple interpolation feature to my component, like `http://www.example.org/{lang}-{country}` so I can serve up my child component by the same host...

Btw. I really love the idea of xcomponents.
I had to dig the source for the still undocument driver API, but it's great.

I'm only curious why the `url` arg is required? Is it for validation purpose?

**Comment by bluepnume** [comment]
Cool, glad the interpolation idea worked!

> I'm only curious why the `url` arg is required? Is it for validation purpose?

Not totally sure I follow the question. Fundamentally, xcomponent just renders an iframe with that url, like `<iframe src="http://www.example.org"></iframe>` -- without the url, what would be displayed in the component's iframe?

**Comment by AndyOGo** [comment]
Sorry my question was not clear.
I mean why does the child (the site which is rendered within the iframe itself) need to know about the url. Because I need to feet both the parent and the child with the create component.

I only see the point that the parent needs to know about the url because the parent with request that app, but why the child?

**Comment by andychong1996** [comment]
Yup, I'm curious about this question as well. Perhaps it just for the sake of the convenience of importing the same file where the `YourComponent.create` is?

**Comment by bluepnume** [comment]
Yep, exactly -- the idea is `xcomponent.create({ ... })` is called in `some-component.js`, then `some-component.js` is loaded in both the parent and the child windows with the exact same settings.

Right now the `url` isn't explicitly used in the child, but that may change in future if we want to verify that the page which is loaded is the correct url for the expected component, before messaging up to the parent etc.

**Comment by AndyOGo** [comment]
@bluepnume thanks for your quick reply.

I see your point. Though I would prefer to split this cody anyway. One parent js and another for the content-window. Saves some bytes and keeps concerns seperated.

**Comment by namirsab** [comment]
@AndyOGo I have a similar situation as you. We are not loading the same file with the same component definition in both the host app and the iframe app. As far as I can see, the only configuration that is required to be the same is the tag. In our case, the tag is dyanmic (so is your url) and what we do is sending it as a query parameter. That way we can get it in the child and use it

**Comment by bluepnume** [comment]
Going to close this for now unless anyone is having any residual issues. Seems like there are at least workarounds possible for the use-cases above. Thanks all!
