### ISSUE TITLE
Uncaught Error: Detected close during init

### ISSUE THREAD

**Issue by andychong1996** [krakenjs/xcomponent#118]
Hi guys,

I recently encounter this error, I'm not sure what this error is. After a quick Google search, I saw that paypal-checkout have encountered this error as well (issue like below), which was solved by @bluepnume. So, any help, please?

[https://github.com/paypal/paypal-checkout/issues/435](url)

This is the stack produced in the console:
<img width="642" alt="screen shot 2017-09-27 at 2 51 03 pm" src="https://user-images.githubusercontent.com/12697240/30899668-69ab59da-a393-11e7-8aa8-141f921d33f8.png">
<img width="644" alt="screen shot 2017-09-27 at 2 51 14 pm" src="https://user-images.githubusercontent.com/12697240/30899672-6c77b69a-a393-11e7-8132-b0fc313a9506.png">

**Comment by bluepnume** [comment]
Which version of xcomponent are you using?

**Comment by andychong1996** [comment]
@bluepnume 1.0.112

**Comment by andychong1996** [comment]
@bluepnume Sorry, I will try update the plugin, and test it again.

**Comment by andychong1996** [comment]
@bluepnume Hi, I'm updating from version 1.0.112 to 5.0.3, and encounter this error, 

> Uncaught Error: Can not find frame with name: undefined

Any help? Thank you.

**Comment by andychong1996** [comment]
@bluepnume I found out that the error above raise because it cannot find the window.name.
And I found that [https://github.com/krakenjs/xcomponent/blob/820a42521cbde1b8c78a52bc09c98bd2eaf487a1/src/component/window.js#L64](url) is where it deconstructing the window.name.
But from the console screenshot, the only key I found that match with the amount of deconstruction key is windowName, but I have no idea where it is being assigned to window.name.

<img width="641" alt="screen shot 2017-09-27 at 5 27 09 pm" src="https://user-images.githubusercontent.com/12697240/30906112-69d3756c-a3a9-11e7-814d-21dda142ca5d.png">
<img width="643" alt="screen shot 2017-09-27 at 5 27 26 pm" src="https://user-images.githubusercontent.com/12697240/30906115-6b880314-a3a9-11e7-9259-5569fd6a819c.png">
<img width="953" alt="screen shot 2017-09-27 at 5 59 01 pm" src="https://user-images.githubusercontent.com/12697240/30907571-96606c76-a3ad-11e7-8f08-a72f3ed74675.png">
