### ISSUE TITLE
Uncaught Error: Can not find frame with name: undefined

### ISSUE THREAD

**Issue by andychong1996** [krakenjs/xcomponent#120]
Hi @bluepnume ,
 I'm updating from version 1.0.112 to 5.0.3, and encounter this error:

`Uncaught Error: Can not find frame with name: undefined`

 I found out that the error above raise because it cannot find the window.name.

And I found that [https://github.com/krakenjs/xcomponent/blob/820a42521cbde1b8c78a52bc09c98bd2eaf487a1/src/component/window.js#L64](url) is where it deconstructing and assign the window.name.

But from the console screenshot, the only key I found that match with the deconstruction assignment is windowName, but I cannot find where windowName is being assigned to window.name.  Perhaps I'm in the wrong direction.

<img width="641" alt="screen shot 2017-09-27 at 5 27 09 pm" src="https://user-images.githubusercontent.com/12697240/30906112-69d3756c-a3a9-11e7-814d-21dda142ca5d.png">
<img width="643" alt="screen shot 2017-09-27 at 5 27 26 pm" src="https://user-images.githubusercontent.com/12697240/30906115-6b880314-a3a9-11e7-9259-5569fd6a819c.png">
<img width="953" alt="screen shot 2017-09-27 at 5 59 01 pm" src="https://user-images.githubusercontent.com/12697240/30907571-96606c76-a3ad-11e7-8f08-a72f3ed74675.png">

**Comment by bluepnume** [comment]
Hi @andychong1996 -- are you loading `5.0.3` in both the parent and child window? "Can not find frame with name" is not an error message which should exist in  `5.0.3`...

**Comment by andychong1996** [comment]
Hi @bluepnume ,

this is the version in my yarn.lock:
`xcomponent@^5.0.3:
  version "5.0.3"
  resolved "https://registry.yarnpkg.com/xcomponent/-/xcomponent-5.0.3.tgz#2e8261f643f94e4d3dbf544d8ffad6cdf6bdf62a"
  dependencies:
    beaver-logger "^3"
    cross-domain-safe-weakmap "^1.0.8"
    cross-domain-utils "^1.0.5"
    hi-base32 "^0.1.1"
    post-robot "^7.0.1"
    zalgo-promise "^1.0.4"`

**Comment by andychong1996** [comment]
Hi @bluepnume ,
I found the problem, the source is from an abstracted docker service. Seems that the codebase in the container is not in sync. Thanks for the help and the team for building such great library!

**Comment by bluepnume** [comment]
Awesome! Glad it's working now
