### ISSUE TITLE
Question: How to access parent component reference?

### ISSUE THREAD

**Issue by freshfunkee** [krakenjs/xcomponent#123]
This is a cool library. I've been making good progress with using it, but I've hit a hurdle.

I'm trying to re-render, or update the properties passed to the child, in order to update the component. I've seen two possible ways of achieving this:
- using `close` (referenced here: https://github.com/krakenjs/xcomponent/blob/08ad03f7b483c52ab661d4b1c32dc3e395f7a8d8/src/component/parent/index.js#L947), and calling `render` with the new prop values
- using `updateProps` (referenced here: https://github.com/krakenjs/xcomponent/blob/08ad03f7b483c52ab661d4b1c32dc3e395f7a8d8/src/component/parent/index.js#L524), along with `xchild.onProps`, and handling the re-render internally, which would be preferable.

However, I'm struggling to get the parent reference in the first place (which I assume contain the api for `close`, and `updateProps`). `xcomponent.create` returns a `Component` reference. `Component.render` returns a `ZalgoPromise`, and the `ZalgoPromise` resolves with undefined. 

I'm out of ideas. I've tried trawling through the docs and examples to no avail. I've also browsed through past issues, but no dice. I might have gone too deep at this point. It's probably staring at me in the face.

Any help would be greatly appreciated

**Comment by freshfunkee** [comment]
Ok, so I think I found the answer. The `ParentComponent` reference can be accessed using `this` within a `props` function. 

However, what I'm trying to accomplish then becomes complicated. I have 2 Xcomponents on the page. When an item in the list of Component 1 is selected, in need Component 2 to be updated with the selected value. 

What would your recommended approach be?
- Register a function within Component 2 that can be called externally? (As in issue #53)
- ???

With regards to the intended approach for obfuscation for the consumer of the components I am creating; I think this may a little too complex for a third party to implement. I haven't tried further obfuscating these callbacks, which should be possible using `def` values. Any thoughts on this approach?

**Comment by freshfunkee** [comment]
Found a better solution: `Component.init(props)`
https://github.com/krakenjs/xcomponent/blob/6ffb3e91e3afc45213105e163522047efe36679b/src/component/component/index.js#L408

This function returns the `ParentComponent` I was looking for. Follow up with `ParentComponent.render(elementRef)` to render the component.

The struggle for `docs` is real 😂

**Comment by chemoish** [comment]
@freshfunkee Are you saying is that we shouldn't use the drivers and instead make your own? 🤐 (I am looking at the react one).
