### ISSUE TITLE
Popup getting opened as tab in Safari 9.1.1

### ISSUE THREAD

**Issue by kms-ky-truong** [krakenjs/xcomponent#125]
Hi @bluepnume,

When clicking on these below link, the button consistently redirects to a new tab rather than the expected popup.
https://developer.paypal.com/demo/checkout/#/pattern/client
http://bluesuncorp.co.uk/icv4/popup.htm

The console error: _Blocked a frame with origin "https://developer.paypal.com" from accessing a frame with origin "https://www.sandbox.paypal.com”. Protocols, domains, and ports must match._

Tested on Safari 9.1.1 (11601.6.17) on OS X El Capitan 10.11.5.

FYI - Safari 10.1.2 (12603.3.8) is working fine.

Not sure if it relates to these issues or not:

- https://github.com/krakenjs/xcomponent/issues/104
- https://github.com/krakenjs/xcomponent/issues/107

Thanks,
Ky

**Comment by bluepnume** [comment]
Hi @kms-ky-truong -- thanks for the report. I'll try to repro.

For the error you see -- `The console error: Blocked a frame with origin "https://developer.paypal.com" from accessing a frame with origin "https://www.sandbox.paypal.com”. Protocols, domains, and ports must match.` -- can you share the line number and/or stack trace?

**Comment by kms-ky-truong** [comment]
Hi @bluepnume,

I keep getting error `You can't comment at this time.`

Thanks,
Ky

**Comment by bluepnume** [comment]
OK. I don't think these errors are related -- the script does a try/catch to detect if the window is closed, but some versions of safari decide to log the errors/warnings anyway. 

I'll try to repro the new-tab problem in Safari 9. Sometimes this is controlled by browser-level settings; the browser can ignore the height/width specified and just force the page into a new tab.

**Comment by kms-ky-truong** [comment]
Thanks @bluepnume. 
FYI - one of my clients reported that he ran into the same issue with Safari 10.0.3 (12602.4.8). However, I don't have a chance to reproduce the issue on Safari 10.0.3.

**Comment by bluepnume** [comment]
Is this setting enabled?

<img width="574" alt="screen shot 2017-11-22 at 8 13 55 pm" src="https://user-images.githubusercontent.com/1219075/33158810-07a998a4-cfc2-11e7-8faa-0abe30d70c3f.png">

**Comment by kms-ky-truong** [comment]
No. It is "Automatically".

Today I cannot reproduce the issue on Safari 9.1.1 anymore.

https://developer.paypal.com/demo/checkout/#/pattern/client
http://bluesuncorp.co.uk/icv4/popup.htm
Are the above links using the latest version which may fix the issue?

Thanks,
Ky

**Comment by bluepnume** [comment]
Yeah, that page is generally updated with the latest version. But there hasn't been any specific fix for this issue. Let me know if it crops up any more.

**Comment by kms-ky-truong** [comment]
Hi @bluepnume,

I believe there is nothing to do with xcomponent version. 
I verified my web app which is still using the very old version of xcomponent and the issue has gone. Weird!

I'm asking my client to verify the issue on Safari 10.0.3...

Thanks,
Ky

**Comment by bluepnume** [comment]
Is it possible Safari was in full-screen mode last time you were testing? That will also force any new windows into a full-screen tab.

**Comment by kms-ky-truong** [comment]
Yes, you're correct.
Safari 9.1.1 opens the page as tab when it is in full-screen mode.

So this is still an issue?

Thanks,
Ky

**Comment by bluepnume** [comment]
It's problematic, but I think it's essentially unsolvable. I think xcomponent authors probably just need to be aware that there are times when popups will load in new tabs. I'll make a note to add this to the docs.

**Comment by kms-ky-truong** [comment]
Thanks for your info.
Closing the issue...
