### ISSUE TITLE
Height 100% on dimensions doesn't work

### ISSUE THREAD

**Issue by silverlight513** [krakenjs/xcomponent#128]
I have a component that I'm trying to get loaded using xcomponent. This component tries to be completely responsive, by which I mean that it only shows as much content as it can with the space it was given. 

If I have a div on the page that is 400px by 400px, then I want the component to take up that whole space. I've done this by setting the dimensions to 100% for width and height. 

The issue I've found is that the height of the iframe itself is always 0px. This is because of a wrapper div around the iframe (both created by xcomponent). This div is the one with the class `xcomponent`.

Temporarily I've fixed this by grabbing the element and setting the styling `height: 100%;` on it.

I've noticed that xcomponent is using this div to set styles on it's children. I am proposing that we set `height: 100%;` on the div when setting those styles.

On the image below I've highlighted the div that's causing the issue. The div with the ID `widget-container` is the element I pass to the render function of the xcomponent instance.
![image](https://user-images.githubusercontent.com/4225358/31998862-3024a7a0-b989-11e7-9ae4-a7959c9d98df.png)

**Comment by bluepnume** [comment]
That's weird. When I tested it, I see the `class="xcomponent"` element taking up 100% of the height and width:

<img width="1281" alt="screen shot 2017-10-25 at 10 45 04 am" src="https://user-images.githubusercontent.com/1219075/32013991-b0ed08b8-b971-11e7-8dec-11b28a43d5ec.png">

Do you have a minimal example or a jsfiddle that I can see to replicate the issue?

**Comment by silverlight513** [comment]
Hey @bluepnume, I just spent some time making a repro of the problem I'm experiencing. 
https://github.com/silverlight513/xcomponent-test

Below are two screenshots that show how `div.xcomponent` is collapsing the height inside the wrapper div.

Wrapper div:
![image](https://user-images.githubusercontent.com/4225358/32054518-87e5f93a-ba56-11e7-90ef-7487c24149ea.png)

`.div.xcomponent`
![image](https://user-images.githubusercontent.com/4225358/32054535-9601344e-ba56-11e7-9eb3-b14d923a33c0.png)

**Comment by bluepnume** [comment]
Aha! Figured it out. The reason I wasn't seeing it in my demo page was, the demo page didn't have a `<!DOCTYPE html>`. That ends up changing the behavior of `height: 100%;`.

I'll have a fix in for this shortly.

**Comment by bluepnume** [comment]
OK, fixed and published! Can you try with `6.0.16`?

**Comment by marksmithson** [comment]
I work with Jack @silverlight513 and have confirmed that 6.0.16 fixes this issue for us. Thanks!

**Comment by bluepnume** [comment]
Awesome! Thanks for checking
