### ISSUE TITLE
Notify child when a parent prop/value changes

### ISSUE THREAD

**Issue by cmackenz** [krakenjs/xcomponent#130]
Struggling a little bit on what seems like an easy concept.

I am passing props down to my child component and that works fine, but I want my child component to re-render when the a parent value changes. 

A trivial example would be something like:

```
  let counter = 0;
  setInterval(() => {
    counter++;
  }, 1000);

  COUNTER_WIDGET.render({
    counter,
  }, '#counter');
```

And then in my child component (Ember)
```
export default Ember.Route.extend({

  setupController(controller, model) {
    this._super(...arguments);
    set(controller, 'attrs', {
      counter: window.xprops.counter,
    })

    setInterval(() => {
      console.log('window.xprops.counter', window.xprops.counter);
      // Always 0
    }, 1000)
  },

})
```

How do I get the new value of `counter` in my child component when it has been updated on the parent?

**Comment by freshfunkee** [comment]
Not sure if you already received an answer, but a child component gets notified of property changes via the `onProps` function.

What you'll be looking for in your child component would be:
```
window.xchild.onProps(function (props) {
  console.log(props.counter);
});
```

**Comment by cmackenz** [comment]
Thanks @freshfunkee, that's what I was looking for!
