### ISSUE TITLE
Demo - Angular(JS) demo no longer functions

### ISSUE THREAD

**Issue by ltomes** [krakenjs/xcomponent#135]
The angular(JS) demo for xcomponent is no longer functioning in latest chrome (Version `62.0.3202.94`).

http://krakenjs.com/xcomponent/demo/frameworks/angular/index.htm

This is not blocking me in any way I just figured I would mention it so the demo can be removed or updated. Have a good day!

[krakenjs.com-1512161224334.log](https://github.com/krakenjs/xcomponent/files/1522927/krakenjs.com-1512161224334.log)

**Comment by bluepnume** [comment]
Fixed! Thanks for the heads-up
