### ISSUE TITLE
Url Mapping doesn't seem to have a purpose

### ISSUE THREAD

**Issue by adamtaylor13** [krakenjs/xcomponent#142]
I've looked all over the API docs and I cannot seem to find a purpose for the `url` attribute when used as a map. Based on the API docs it seems that I have to change the `defaultEnv` string every time I want to use a different environment. If that's the case, it would be easier to keep commented-out lines like:
`// url: 'localhost:3000`
`// url: 'app.com`
`// url: 'test.app.com`

and simply uncomment whichever env I need.

I hope I'm wrong. Is there a way env can be dynamically set/inferred from the url where the project is located?
Sorry if I'm overlooking something obvious. I've read the api docs twice and can't figure out why this feature might be here.

**Comment by bluepnume** [comment]
This lets people rendering your component decide which env they want to use. They can call 

``FooComponent.render({
    env: 'sandbox'
}, '#container')
```

-- and xcomponent will use that `env` to decide on the most appropriate url to use.

**Comment by adamtaylor13** [comment]
Oh I see! That makes sense. Is this documented in the api docs?

If so, could I contribute by linking to that section in the section that the `url` map is defined?
If not, could we add that?
