### ISSUE TITLE
Resizing container with autoResize does not work

### ISSUE THREAD

**Issue by ruhusobeje** [krakenjs/xcomponent#144]
@bluepnume

In the xcomponent.create I have:

autoResize: {
    height: true,
    width: true
}
But it does not autoresize.

I tried to pass a prop from parent resizeParent:function(){ window.resize('100%', '100%');}
Then, calling window.xprops.resizeParent();

I have a react component as child. It is a list of items.
I would like to resize parent container once there are more/less items in the child.

But that did not work as well 😟

Thanks!

**Comment by jelohe** [comment]
I had the same problem with autoResize until i added an `element` property pointing to a css selector of my embedded app. I couldn't find this behavior on the docs.

`
autoResize {
  height: true,
  width: true,
  element: '.my-selector'
}
`

**Comment by ruhusobeje** [comment]
@jelohe 
You are the savoir! Worked great.
Thanks a lot 😃

**Comment by ruhusobeje** [comment]
@bluepnume 
Would you like to add it to docs?
Should I make a pull request to add the info?

**Comment by jelohe** [comment]
#148: Let me know if this makes it clear.
