### ISSUE TITLE
Enhancement: Add Custom Attributes to the iFrame

### ISSUE THREAD

**Issue by rjdlee** [krakenjs/xcomponent#145]
If the contents of the iFrame requires access to geolocation, camera, or audio, you need to set an attribute on the iFrame (https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes).

I tried doing the following, but it gets overwritten by something:
```
xclogin.LoginXComponent.render({...}, '#container').then(() => {
          const iframe = document.getElementById('container').querySelector('iframe');
          iframe.setAttribute('allow', 'camera');
})
```

**Comment by bluepnume** [comment]
You can do this today -- see example here:

https://github.com/paypal/paypal-checkout/blob/master/src/button/component.jsx#L156-L160

```
    attributes: {
        iframe: {
            foo: 'bar'
        }
    }
```

**Comment by rjdlee** [comment]
Thanks, might be a good idea to add it to the documentation.
