### ISSUE TITLE
Error: Unexpected onresize message from domain https://localhost2 -- expected message from https://localhost

### ISSUE THREAD

**Issue by steveoliver** [krakenjs/xcomponent#149]
Super excited to have found this!  Thanks, @bluepnume!

I cloned xcomponent-demo and renamed it fsxc.wizard here: https://github.com/steveoliver/fsxc

I'm testing a local implementation between two hosts (localhost, embedding localhost2).

But I'm getting this ````Error: Unexpected onresize message from domain https://localhost2 -- expected message from https://localhost```` message in the parent window.

Gist here:

https://gist.github.com/steveoliver/3d4506903aa15475e0ba0ac2d0ed5640

I've searched around for existing issues or documentation, and I've tried the allowedRemoteDomains '*' on localhost (even though I see the default is the * wildcard), so not sure where to look next to resolve this error.

Any thoughts greatly appreciated!

**Comment by bluepnume** [comment]
Strange. I tried the same on my local and didn't see any issues. Can you advise which version of xcomponent you're running? Also, if you're able to deploy this somewhere I so I can repro that would be super useful. Thanks!

**Comment by steveoliver** [comment]
Hmm, yeah, as expected: https://steveoliver.github.io/fsxc/demo/iframe/index.htm works fine.  I wonder if my janky ass local SSL cert is mixing up the awesome?

**Comment by steveoliver** [comment]
Well yeah, it's the same domain here.. lemme set up another parent domain.

**Comment by steveoliver** [comment]
Yep - still works at http://circatree.com/dev/fsxc/demo/iframe/index.htm.  Will check my local setup.

**Comment by steveoliver** [comment]
Weird, still an issue on http://localhost<-->localhost2

**Comment by bluepnume** [comment]
Strange. I'm scratching my head here; xcomponent should pick up on the url you specify and use it to listen on the right domain.

Can you set a breakpoint here and see which `domain` is being passed? https://github.com/krakenjs/xcomponent/blob/master/src/component/base.js#L152

**Comment by steveoliver** [comment]
I've been testing the demo ... which doesn't pass the url, only 'demo' env.  I'll set up my custom implementation to test.

**Comment by bluepnume** [comment]
In your gist you had `url: 'https://localhost2/fsxc.iframe.html'` -- that's the url I meant.

**Comment by steveoliver** [comment]
Yeah, I'll post that up

**Comment by steveoliver** [comment]
There it is: http://circatree.com/dev/fsxc/demo/custom/fsxc.html

**Comment by bluepnume** [comment]
Yeah, I see the problem now. You shouldn't pass a `url` in the `render()` call. You've already configured the urls in `xcomponent.create()`. You can just pass the `env` in render and things should work.

**Comment by Cono52** [comment]
I'm getting a similar error but im not feeding in any URL into the render method.
`
const Widget = create({

  tag: 'my-widget',
  // What are the url's the widget will be accessible from?
  url: {
    dev: 'http://localhost:3001',
    prod: 'example.host.com'
  },

  defaultEnv: 'prod',

  allowedParentDomains: [
    '*'
  ],
`
