### ISSUE TITLE
ReferenceError: __CHILD_WINDOW_ENFORCE_LOG_LEVEL__ is not defined

### ISSUE THREAD

**Issue by MaxMillington** [krakenjs/xcomponent#154]
I started getting this error after upgrading to 6.0.54

``` ReferenceError: __CHILD_WINDOW_ENFORCE_LOG_LEVEL__ is not defined```
```  at Object../src/component/child/index.js (node_modules/xcomponent/dist/xcomponent.js:4922:13) ```

My implementation is fairly straigtforward:

```
const baseUrl = `${window.location.protocol}${window.location.host}`
const url = `${baseUrl}/shop-list/shoplist-button`
xcomponent.create({ tag, url })
```
It worked just fine before the upgrade

**Comment by bluepnume** [comment]
Sorry about this, looks like it got missed in an upgrade. Can you try with the latest version?
