### ISSUE TITLE
How can I change default timeout for ACK_TIMEOUT?

### ISSUE THREAD

**Issue by andychong1996** [krakenjs/xcomponent#49]
I got this error on production environment, but not locally.
Uncaught Error: No ack for postMessage xcomponent_init in 1000ms

I'm here to ask how can I provide the timeout. Thank you.

**Comment by andychong1996** [comment]
We use it on a Shopify plugin, and the XComponentInit send a request to shopify side.
But It took more than 1 sec.
So I need a way to implicitly set the timeout.

**Comment by bluepnume** [comment]
You could try `xcomponent.postRobot.CONFIG.ACK_TIMEOUT = 2000;` -- but I suspect there's a deeper problem here. Post messages are asynchronous, but they should be almost instantaneous, so if a message is timing out after 1000ms it's likely it's failing for some other reason.

Is there code somewhere I can try it?

Also -- messages in xcomponent are restricted by domain. If this a problem with one env and not another, my suspicion would be that there's some mismatched domain. What settings are you using in the component definition?

**Comment by bluepnume** [comment]
I'm guessing this is the module: https://github.com/PostCo/postco-shopify/commits/master

Noticed you reverted xcomponent back to an old version. Were you seeing this issue only with the latest?

**Comment by andychong1996** [comment]
@bluepnume Yes, it only happens on the newer versions, on local development it is fine, maybe it is fast enough, but on production, it sends the request to Shopify. The plugin is mounted on the client Shopify shop's cart page. I can only confirm this problem happens on  v1.0.70, v1.0.80, and v1.0.100. Not sure for the other versions. And it works fine on v1.0.63.

**Comment by bluepnume** [comment]
Oh right, so `https://postco-plugin-production.herokuapp.com/delivery` does a redirect to shopify?

xcomponent uses the specified url to decide which domain to listen to messages from. Can you try setting `domain` to shopify's domain and seeing if it works?

Are you expecting shopify to send callbacks up to you though, through xcomponent?

**Comment by bluepnume** [comment]
Will close this issue soon, let me know if there are any more updates on your side.

**Comment by andychong1996** [comment]
I don't expect Shopify to send callback through xcomponent, but I mount them to different Shopify shops, so I assume I am expecting it.
Basically, the flow is there is a script tag on each Shopify shop that loads the script to mount the xcomponent on, and then target another app to load in the iframe.
By the way, how can I set the domain?

**Comment by bluepnume** [comment]
Hi Andy. Sorry, didn't get a notification for this thread back when you replied. Did you have any luck getting your use-case to work?

If not, please share some example code so I can try to help.

**Comment by harouny** [comment]
@bluepnume I have this error only in IE 11 "Error: No ack for postMessage xcomponent_init in 1000ms"
Same component working fine in Chrome and Firefox.
I'm not specifying any domains settings
My config is something like this
``` javascript
Connector = xcomponent.create({
    tag: 'connector',
    url: "[url to my html page]",
    dimensions: {
        width: '800px',
        height: '400px'
    },
    contexts: {
        popup: true
    },
    defaultLogLevel: 'warn',
    props: {
        getAccessTokenAsync: {
            type: 'function',
            required: true
        },
        selectedAppId: {
            type: 'string',
            required: false
        },
        selectedConnectionId: {
            type: 'string',
            required: false
        },
        onSuccess: {
            type: 'function',
            required: true
        },
        onFailure: {
            type: 'function',
            required: true
        }
    }
});
```
"\xcomponent\demo\basic\popup\index.htm" seems to be working fine in IE 11 so I'm going to have to investigate further

**Comment by bluepnume** [comment]
@harouny are you using xcomponent.js or xcomponent.frame.js?

**Comment by harouny** [comment]
@bluepnume
I'm using xcomponent.js. I wasn't aware of tge IE 11 bridge thingy. Thanks for the hint!

**Comment by bluepnume** [comment]
Let me know if you run into any problems. Also added https://github.com/krakenjs/xcomponent/issues/86 to make this a more obvious failure.

**Comment by harouny** [comment]
@bluepnume
Since I'm not using post-robot directly am I still need to do a) somehow?
a. Use the special ie build of post-robot: dist/post-robot.ie.js.

**Comment by harouny** [comment]
Sorry It will be in the bridge only....thanks :)

**Comment by bluepnume** [comment]
@harouny -- only when you load post-robot in the bridge.html url.

In fact -- you can avoid dealing with post-robot directly just by loading xcomponent or your component in the frame. So in step **b)** you could load `<script src="http://yy.com/js/my-component.js"></script>` or `<script src="http://yy.com/js/xcomponent.js"></script>` which will implicitly pull in post-robot

**Comment by harouny** [comment]
I think a) and b) need to be swiched for clarity

**Comment by bluepnume** [comment]
I agree in the context of xcomponent. When I add bridge docs over here, there's probably no need to mention post-robot at all.

(In fact if you feel like contributing any docs here, please feel free!)

**Comment by harouny** [comment]
Sure mate, I will. Thanks

**Comment by harouny** [comment]
@bluepnume 
I have added "bridgeUrl" to xcomponent.create but still doesn't work. In my page I don't the Iframe and I don't see my bridge html page being loaded in network tap.
I found this code in openBridge method:
``` javascript
if (!this.driver.needsBridge) {
            return;
}
```
But I haven't seen in code anywhere we set driver.needsBridge

Any ideas?

**Comment by bluepnume** [comment]
So, just to be sure -- you're running this in IE, and you're trying to load a component on a different domain, right?

`this.driver.needsBridge` is set to true for popup mode -- are you seeing this condition being hit?

**Comment by harouny** [comment]
Yes, IE and loading a component on a different domain via a popup
Where in code we set ```this.driver.needsBridge``` to true?

**Comment by bluepnume** [comment]
I was gonna point to the code location, then I realized it's not actually there. I think this got missed out in some refactoring. Lemme quickly double check this.

**Comment by harouny** [comment]
OK, cool, somehow good news :)

**Comment by bluepnume** [comment]
OK try the latest code :) removed that check, it's redundant. As usual, great catch.

**Comment by harouny** [comment]
Bridge is working now, thanks for the quick fix!

**Comment by bluepnume** [comment]
Cool! Going to close this now.

**Comment by AlbinoDrought** [comment]
Hey,

Encountered the same issue with my project. Attempted to follow the above steps to no avail. Here's what I did exactly:

- Create a bridge page, including only `xcomponent.js`. Do I need postrobot ie, or my component as well? https://github.com/krakenjs/xcomponent/issues/49#issuecomment-300009747
- Specify `bridgeUrl` on component create, linking to the above page.
- Use this component as a normal popup, in a way that works (and continues to work) in other browsers, cross-domain.

With the above, the error `No ack for postMessage xcomponent_init in 1000ms` is still thrown in IE.

Anyone able to see where I've gone wrong?

Thanks,
Sean

**Comment by kms-ky-truong** [comment]
Hi @AlbinoDrought, 

- You need to include post-robot.ie.js in your bridge page. Sample:

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <script src="/js/post-robot.ie.js"></script>
</body>
</html>
```


- Specify bridgeUrl on component create as below:

```
window.MyXcomponent = xcomponent.create({
      url: "https://mydomain.com/popup",

      bridgeUrl: "https://mydomain.com/bridge.html",

      contexts: {
          popup: true
      },

      dimensions: {
        width: '770px',
        height: '45%'
      },
    .....
})
```


It works well at my end (post-robot v8.0.14 and xcomponent v6.0.37).

HTH,
Ky
