### ISSUE TITLE
How to trigger a function in Child's window from Parent's window

### ISSUE THREAD

**Issue by hafizio** [krakenjs/xcomponent#53]
Is it possible to access a global function defined in the child's window from the parent's window object? Does xcomponent or postRobot have this feature built in?

The use case is, when a user clicks a button in the parent component, I want the child component to respond to the click.

Thanks!

**Comment by bluepnume** [comment]
Hi @hafizio,

The best way to do this at the moment would be to define a function prop, and pass it down:

```
MyComponent.render({

    passMethod: function(method) {
        // now I have access to `method` from the child window
    }

}, '#container');
```

Then call it from the child:

```
window.xprops.passMethod(function() {
    // the parent will be able to call this function
});
```

Does that work for your use-case?

**Comment by hafizio** [comment]
Thanks @bluepnume we'll try the solution and keep you updated. Thanks!

**Comment by hafizio** [comment]
@bluepnume how do I execute the function callback passed into the `passMethod`? Because in the parent `window`, I can only access parent's `props` and not the `passMethod`. In the `props` object in the parent, it only contains the spec for the component and not the function itself.

**Comment by bluepnume** [comment]
@hafizio Not sure I follow. You should be able to just call the function:

```
MyComponent.render({

    passMethod: function(method) {
        method();
    }

}, '#container');
```

The way this works is:

- You render `MyComponent` and pass down your `passMethod` method.
- The child window calls `passMethod`, and passes a method up to the parent
- `passMethod` is called on the parent window, and now has access to the `method` that is passed

Does that make sense?

**Comment by hafizio** [comment]
@bluepnume Thanks for the reply. I tried the exact approach previously, but it doesn't work due to some some cache issues that we have. After disabling the cache, I bind the `method` to the parent's `window` object and it works perfectly.

Thanks a lot for you time!
