### ISSUE TITLE
Apple Pay does not work with xcomponent due to insecure parent frame

### ISSUE THREAD

**Issue by kms-ky-truong** [krakenjs/xcomponent#60]
Hi,

I'm using [Stripe API](https://stripe.com/docs/apple-pay/web) to open Apple Pay within an xcomponent lightbox. However, it throws an error "Trying to call an ApplePaySession API from a document with an insecure parent frame" when it detects the outermost iframe is not secure (not starting with https) as below:
`<iframe name="__lightbox_container__ec6827b044__" scrolling="no" frameborder="0" style="display: block; position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 2147483647;"></iframe>`

Can you please look into?

Here is how I implement the Apply Pay:
```
<style>
  #apple-pay-button {
    display: none;
    background-color: black;
    background-image: -webkit-named-image(apple-pay-logo-white);
    background-size: 100% 100%;
    background-origin: content-box;
    background-repeat: no-repeat;
    width: 100%;
    height: 44px;
    padding: 10px 0;
    border-radius: 10px;
  }
</style>

<button id="apple-pay-button"></button>

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script>
    Stripe.setPublishableKey('pk_test_6pRNASCoBOKtIshFeQd4XMUh');

    Stripe.applePay.checkAvailability(function(available) {
        if (available) {
            document.getElementById('apple-pay-button').style.display = 'block';
        }
    });

    document.getElementById('apple-pay-button').addEventListener('click', beginApplePay);


    function beginApplePay() {
        var paymentRequest = {
            countryCode: 'US',
            currencyCode: 'USD',
            total: {
                label: 'Stripe.com',
                amount: '19.99'
            }
        };
        var session = Stripe.applePay.buildSession(paymentRequest,
            function(result, completion) {

            $.post('/charges', { token: result.token.id }).done(function() {
                completion(ApplePaySession.STATUS_SUCCESS);
                //window.xchild.props.onComplete('Apple Pay succeeded!');

            }).fail(function() {
                completion(ApplePaySession.STATUS_FAILURE);
                //window.xchild.props.onComplete('Apple Pay error!');
                
            });

        }, function(error) {
            console.log(error.message);
        });

        session.oncancel = function() {
            console.log("User hit the cancel button in the payment window");
            //window.xchild.props.onComplete('Apple Pay canceled!');
        };

        session.begin();
    }
</script>
```

Thanks,
Ky

**Comment by bluepnume** [comment]
Are both your parent page and your frame served up over `https`?

This sounds like a restriction with apple-pay, rather than xcomponent. xcomponent will allow non-https pages, but seems like apple-pay is blocking them.

**Comment by kms-ky-truong** [comment]
Hi,

The page and its frames are served up over https, except the outermost iframe I mentioned in the issue. That iframe is generated when the context is 'lightbox' to create the overlay - I guess.

Could you tell me the purposes of that iframe? 
If it is there just to handle the overlay, I can make some changes by myself.

Many thanks,
Ky

**Comment by bluepnume** [comment]
Hi,

That iframe is just used to ensure that the parent page's css doesn't conflict with the css for the overlay. It doesn't have a `src` - and as such it should inherit the domain from the parent window.

I tried your example code, but didn't see any errors when both the parent and the child were rendered using `https`.

Can you possibly link me to your test site so I can see the error and debug? Also, can you let me know which browser you're testing in?

Thanks!

**Comment by bluepnume** [comment]
Any updates on this issue? Otherwise planning to close it as I can't repro.

**Comment by kms-ky-truong** [comment]
Hi @bluepnume,

Sorry for the delay.
I'll fork the kraken-js today and put my implementation there so that you can see the error and debugs.

Thanks,
Ky

**Comment by kms-ky-truong** [comment]
Hi @bluepnume,

Please pull the demo from https://github.com/kms-ky-truong/xcomponentapplepay.
It was generated from kraken-js.

For the demo to work with Apple Pay, you might need to meet its [Minimum Requirements](https://stripe.com/docs/apple-pay/web).

Thanks,
Ky

**Comment by bluepnume** [comment]
Yeah, managed to repro, thanks for sharing the code.

Seems like this check is being done somewhere in `ApplePaySession.canMakePaymentsWithActiveCard` which is a native browser function.

I can probably add a setting to disable rendering the overlay into a new iframe. That was mainly to make sure the stylesheet of the overlay didn't conflict with any existing styles on the parent page.

**Comment by kms-ky-truong** [comment]
That would be awesome. Many thanks for your effort.

**Comment by bluepnume** [comment]
OK, I've added an option for this: `sandboxContainer: false`

```javascript
xcomponent.create({
    sandboxContainer: false
});
```

I tried this with your code and I now see the apple pay button. Can you give it a try on your side? Thanks!

<img width="419" alt="screen shot 2017-03-22 at 6 08 26 pm" src="https://cloud.githubusercontent.com/assets/1219075/24227482/9b4ff6ba-0f2a-11e7-8215-79e71e82d844.png">

**Comment by kms-ky-truong** [comment]
It works now.
Much thanks for your effort.

-- Ky
