### ISSUE TITLE
Parent to child messaging feature

### ISSUE THREAD

**Issue by marcelolorenzati** [krakenjs/xcomponent#61]
xcomponent defines child to parent but no parent to child messaging that would be of great value to have parent to iframes comunicated.

**Comment by bluepnume** [comment]
@marcelolorenzati this is exactly what we have planned through https://github.com/krakenjs/xcomponent/issues/54 :)

For now though, you could just pass a callback up to the parent with the functions you want to expose:

Parent:

```
MyComponent.render({

    passActions: function(actions) {
        actions.foo();
    }
});
```

Child:

```
window.xprops.passFunctions({
    foo: function() { ... },
    bar: function() { ... }
})
```
