### ISSUE TITLE
A prop for showContainer would be good

### ISSUE THREAD

**Issue by jmc265** [krakenjs/xcomponent#65]
I think the container should be optional. So when creating a popup:

```myComponent.renderPopup({showContainer: false});```

should end up with the popup created and no lightbox covering the parent.

**Comment by bluepnume** [comment]
You can blank out the `parentTemplate` in the component definition:

```
window.MyLoginComponent = xcomponent.create({

    // The html tag used to render my component

    tag: 'my-login-component',

    // The url that will be loaded in the iframe or popup, when someone includes my component on their page

    url: './login.htm',

    // The size of the component on their page

    dimensions: {
        width: 250,
        height: 150
    },

    parentTemplate: '',

    // The properties they can (or must) pass down to my component

    props: {

        prefilledEmail: {
            type: 'string',
            required: false
        },

        onLogin: {
            type: 'function'
        }
    }
```

Note -- if you want to do the same for lightbox, the iframe still needs to have some element to render into, so I'd recommend doing:

`parentTemplate: '<div class="{CLASS.ELEMENT}"></div>'`

But note you'd need to add some styles here to do centering, etc. The default parent template is here for reference: https://github.com/krakenjs/xcomponent/blob/master/src/component/component/templates/parent.htm
