### ISSUE TITLE
Auto-resizing of parent

### ISSUE THREAD

**Issue by bluepnume** [krakenjs/xcomponent#7]
I should be able to specify `autoResize: true` and have my lightbox automatically resize itself to match the size of the child window body size.

For example

```javascript
let FooComponent = xcomponent.create({
    ...
    autoResize: true
});
```

Should probably use a `setInterval` loop in the child and `postMessage` up to resize if the `document.body` size changes.

Note -- unless we can find a way to resize popup windows outside of user interaction events, this is probably just going to have to be limited to lightboxes.

**Comment by bluepnume** [comment]
Mostly working but still buggy in IE and Firefox.

**Comment by bluepnume** [comment]
Almost there. Requires further testing / bug-fixes in IE.

**Comment by hafizio** [comment]
Does `autosize` option works with usual iframe? (not a lightbox).

**Comment by bluepnume** [comment]
It should do, yes. I just ran a quick test and it seems to work.

**Comment by vigosan** [comment]
Is this feature still working on master? I'm trying to embed using an iframe, but it is not auto resized:

![screen shot 2017-06-14 at 2 47 29 pm](https://user-images.githubusercontent.com/767/27132903-c07bb10e-5110-11e7-879e-faa773cfe7b7.png)

![screen shot 2017-06-14 at 2 49 13 pm](https://user-images.githubusercontent.com/767/27132916-c5130d5c-5110-11e7-9915-c834f6dce6ea.png)

Am I missing something in the configuration? thx
