### ISSUE TITLE
Question: how do I get rid of all the logs created by xcomponent in the console? Is there a prop I can set?

### ISSUE THREAD

**Issue by mmairs9** [krakenjs/xcomponent#74]

**Comment by bluepnume** [comment]
Hey @mmairs9 -- most of the functionality for this is already built as part of https://github.com/paypal/paypal-checkout/issues/180, I just need to expose it as an option when creating xcomponents. I'll keep you posted.

**Comment by raphaelcosta** [comment]
👍

**Comment by harouny** [comment]
@bluepnume 
Hi Daniel, 
I started to work on this item. I had a question: Is the intention is to use props as the only way of communication between host and components? so for example will we have (logLevel) as an internal prop with the default 'info' then when then host wants to change that it pass ('warn', 'error', 'debug') as a value for logLevel prop?

**Comment by bluepnume** [comment]
Hey @harouny -- that's exactly right. If you're looking for an example, here's how I'm doing it over in `paypal-checkout`: https://github.com/paypal/paypal-checkout/commit/a675143f40e77aa52614e83b0d33d43e00db9229

I'm thinking log-level should be an option when you first create the component, and that should be the default log-level that's passed down to the child.

**Comment by harouny** [comment]
@bluepnume cool, I will submit a PR soon

**Comment by bluepnume** [comment]
Fixed and published, thanks for the fix @harouny!
