### ISSUE TITLE
Disable Logging from xcomponent

### ISSUE THREAD

**Issue by Enijar** [krakenjs/xcomponent#75]
Is there an option to disable all of the `console.log`s in xcomponent? I can't see an option in the docs.

![screen shot 2017-04-03 at 17 39 39](https://cloud.githubusercontent.com/assets/5284715/24620187/9e2b7954-1894-11e7-963d-5a903a7cab48.png)

**Comment by bluepnume** [comment]
Hey, this option doesn't exist yet but it's definitely planned. Please see https://github.com/krakenjs/xcomponent/issues/74
