### ISSUE TITLE
There is something wrong with sendLogsToOpener

### ISSUE THREAD

**Issue by jmc265** [krakenjs/xcomponent#78]
I have localhost:8005 open a popup to localhost:8004 via xcomponent. My logs from the localhost:8004 popup get sent to localhost:8005.

Looking at the code:
https://github.com/krakenjs/xcomponent/blob/acc8145a93f974dd118dc489740143e13423f263/src/component/child/index.js#L211
this does not seem to be expected. 
The isSameDomain() check comes back true for one of the iterations and therefore the continue statement does not happen. 
I am finding it hard to debug this any further because I am debugging the disted code but happy to try and get more details if needed.

At the very least, could be have an option here to turn this feature on/off?

Thanks,
James

**Comment by bluepnume** [comment]
Yeah I'm going to disable this and put it behind a flag. This is an experimental feature we're using for paypal checkout, pretty sure it will be of marginal value to others.

**Comment by bluepnume** [comment]
Alright -- can you try with the latest version? Published with this off by default.

**Comment by jmc265** [comment]
Thanks, version 2.0.20 has fixed the behaviour.
