### ISSUE TITLE
xcomponent.frame.js import is not creating post robot bridge

### ISSUE THREAD

**Issue by mmairs9** [krakenjs/xcomponent#79]

**Comment by mmairs9** [comment]
postRobot.bridge.linkUrl is undefined - We are attempting to use xcomponent with just iframe support for better performance

**Comment by bluepnume** [comment]
Which version are you running? This should have been fixed by this commit: https://github.com/krakenjs/xcomponent/commit/2124deef3dc17dba265b995fb2bf5c6f93ef470b

**Comment by mmairs9** [comment]
I just updated to latest version and its working well now - loads a good bit quicker 👍 . Thanks Again!

**Comment by bluepnume** [comment]
Great!
