### ISSUE TITLE
"Cannot read property 'Ua' of undefined" in v2.0.23

### ISSUE THREAD

**Issue by emiloberg** [krakenjs/xcomponent#81]
When upgrading (`yarn remove xcomponent && yarn add xcomponent`) from 2.0.22 to 2.0.23, I'm getting the following error in my browser console:

```
Cannot read property 'Ua' of undefined
```

![skarmavbild 2017-04-24 kl 13 17 56](https://cloud.githubusercontent.com/assets/4673048/25335629/23bea36a-28f4-11e7-8310-79a31d0f3d6f.png)

When trying to figure out why this is happening I built the dist files from the repo (as of 7f83bf2) and copied into my node_modules. Interesting enough, everything is then working fine. Which leads me to believe that the dist folder on npm is not up to speed, could this be correct?

Building this way:
```
git clone ...
npm install
./node_modules/.bin/gulp build
cp dist/xcomponent.js xxx/node_modules/xcomponent/dist
```

**Comment by harouny** [comment]
I can produce same error in 2.0.23

**Comment by sonoman** [comment]
Demo Site is throwing the same error.

**Comment by bluepnume** [comment]
Fixed. Thanks for the heads up. I had uglify prop-mangling enabled on my local when I merged and built the latest PR. Gotta add something to my publish script to prevent any un-staged changes making it into /dist. Sorry all!

**Comment by sonoman** [comment]
fix is working. thanks for the prompt response !
