### ISSUE TITLE
xcomponent.frame.js undefined popUpWindow.

### ISSUE THREAD

**Issue by mmairs9** [krakenjs/xcomponent#83]
Receiving Js Error popupWindowsByWin is undefined in latest dist version of  xcomponent.frame.js in the cleanUp function __WEBPACK_IMPORTED_MODULE_0__global__.a.popupWindowsByWin.delete(win);

Should it have reference to popUp window?

**Comment by bluepnume** [comment]
Checking on this, thanks for the catch. I suspect this needs to be conditionally excluded from the frame-specific build.

**Comment by bluepnume** [comment]
Should be fixed, can you try the latest published version?

**Comment by mmairs9** [comment]
Awesome this looks to have been fixed no longer seeing the error. I did notice that the default log functionality that was recently added  did not seem to be take effect with xcomponent.frame.js. 

I have it set as 
defaultLogLevel: 'error'

**Comment by harouny** [comment]
@mmairs9 
Its logLevel:'error' 
please try and let me know

**Comment by harouny** [comment]
Sorry my bad.... defaultLogLevel when creating component and logLevel in props when rendering component.

**Comment by bluepnume** [comment]
Glad defaultLogLevel works for you!

**Comment by bluepnume** [comment]
That's weird -- let me take a look. The frame build should include all of the log-level related code...

**Comment by mmairs9** [comment]
this looks good to me now!

**Comment by bluepnume** [comment]
Oh glad it works -- didn't actually fix anything, maybe you had an old version? Closing this issue anyway.
