### ISSUE TITLE
How to handle load errors?

### ISSUE THREAD

**Issue by emiloberg** [krakenjs/xcomponent#85]
Is there a way to handle errors such as "The iframe couldn't be loaded". I'm thinking an `onError` prop on the (in my case) React component.

**Comment by bluepnume** [comment]
`paypal.Button.render()` returns a promise, so you can use onError or simply `paypal.Button.render().catch(function(err) { ... })`.

That said, please do post any specific errors here too so we can look into resolving them.

**Comment by emiloberg** [comment]
Not really following how that would that work in a React environment.

I do a 

```
const foo = xcomponent.create(...)
<foo.react .../>
```

(Will move that to a `xcomponent.driver('react')`)

If I attach an `onError` prop to the React component, that isn't getting called if the iframe fails to load.

N.b. There's no errors with xcomponent itself, this is just me wanting to log if the iframe fails to load for some reason. Always nice to have the logging service ping us if something fails for a lot of users.

**Comment by bluepnume** [comment]
Oh whoops, sorry -- answered your question first thing in the morning while I was still waking up and assumed it was over on the `paypal-checkout` repo.

`onError` is definitely the way to go here, and if it's not being called that's a bug. How are you causing the iframe to not load correctly to test this?

**Comment by emiloberg** [comment]
Hahaha! :sleeping:

I'm just doing a simple test trying to load the iframe from a url which doesn't resolve (nice way of saying that I hammer on the keyboard and do something like this `xcomponent.create({ ..., url: "http://www.asdfasdfasdfasfdasf.com" })`)

**Comment by bluepnume** [comment]
Ah gotcha.

Yeah so unfortunately, the browser doesn't give a way to detect whether an iframe loaded successfully or not if you're hitting an invalid url:

```
(function() {

  var iframe = document.createElement('iframe');
  iframe.src = 'http://www.asdfasdfasdfasfdasf.com';

  iframe.onload = function() { console.log('loaded!'); };
  iframe.onerror = function() { console.log('error!'); };

  document.body.appendChild(iframe);

})();
```

This fires `onload` no matter what the url.

What you can do is set a `timeout: 3000` in the xcomponent definition which will call `onError` if it doesn't get a message from the child in a certain amount of time. Not ideal but probably the best that's possible, unless you have any other ideas.

**Comment by bluepnume** [comment]
(and yet another great reason I really have to get round to adding some more api docs for this...)

**Comment by emiloberg** [comment]
Gotcha!

Doing it pretty the timeout way right now, albeit a bit custom. When the iframe is loaded and have done it's magic it's calling a custom onReady callback on the parent. If that's not called within the timeframe I throw an error. 

As the http status code is only available in the response header (which for obvious reasons isn't readable by the parent), as I see it, the timeout way is the way to go.

Cheers!

**Comment by nishantgupta2501** [comment]
timeout and OnError is not working for me, my component definition is 
window.MyChatComponent = zoid.create({
                    // The html tag used to render my component
                    tag: 'my-chat-component',
                    // The url that will be loaded in the iframe or popup, when someone includes my component on their page
                    url: defaults.babbleUrl,
                    autoResize: {
                        height: true,
                        element: '.minimized-chat',
                    },
                    dimensions: defaults.dimensions,
                    timeout: 6000,
                    onError: defaults.chatOutageCallBack
                });
first of all above definition doesn't set the properties and when i manually set the timeout and onError at runtime, even then it doesn't call the onError function. 
Am i doing something wrong? basically i just want to display a custom error message when my url is not resolved or down
