### ISSUE TITLE
Error when closing popup in IE 11

### ISSUE THREAD

**Issue by harouny** [krakenjs/xcomponent#87]
I have prepared some demo to reproduce this in:
https://github.com/harouny/xcomponent/tree/feature/bridgeDemo

- Clone https://github.com/harouny/xcomponent/
- Switch to feature/bridgeDemo
- npm install
- Based on your enviroment map "localhost.parents.com" and "localhost.children.com" to your localhost. (In Windows using hosts file)
- Run "npm run serve-all"
- Open IE 11
- Navigate to: http://localhost.parents.com:8081/demo/advanced/ie11-cross-domain-popup/index.htm
- Click on "Popup Log In" button
- Fill log in details in the pop up and click "Log In"
-  **Notice error: "Permission denied Error: Permission denied at sendMessage - promise.js " in parent window console.**
- Click on "Popup Log In" again
- **Notice error: "The remote server machine does not exist or is unavailable - bridge.js"**
- **Notice that: filling log in details again then clicking "Log In" will not work.**

**Comment by harouny** [comment]
@bluepnume FYI I'm also trying to know what is happening

**Comment by bluepnume** [comment]
Hey @harouny thanks for the detailed steps. Let me try this out tomorrow and get back to you.

**Comment by harouny** [comment]
@bluepnume Its super difficult to debug this through in IE 11. Any luck finding a clue?

**Comment by bluepnume** [comment]
> Its super difficult to debug this through in IE 11

Welcome to my world :D 

I've pulled your code and I'm seeing the issue anyway. Should be able to figure something out.

**Comment by bluepnume** [comment]
OK @harouny can you try the latest build?

Turns out IE was erroring out if you even reference a closed popup window from the bridge. Added a few strategic try/catches and it solved the problem for me. I'm now able to use your example repeatedly with no errors or issues.

**Comment by harouny** [comment]
@bluepnume Great! It works fine.
