### ISSUE TITLE
In Safari - Find a way to omit dev console errors

### ISSUE THREAD

**Issue by harouny** [krakenjs/xcomponent#88]
xcomponent isSameDomain function produces this error in Safari dev console:

```"Blocked a frame with origin "[url]" from accessing a cross-origin frame."```

There is a try/catch block around the call that causes the error, however Safari decides to still log the error.

**Comment by bluepnume** [comment]
Agreed, would love to find a way to suppress this properly. 👍

**Comment by harouny** [comment]
Not sure if that's even possible but worth to check :)

**Comment by bluepnume** [comment]
Think I might have found the perfect way:

```javascript
let windowIsCrossDomain = Boolean(Object.getOwnPropertyDescriptor(win, 'location').enumerable);
```

This **seems** to consistently give back the correct result for cross domain windows, and doesn't trigger any errors in safari.

**Comment by bluepnume** [comment]
Fixed and published. I'll roll out paypal-checkout with the fix too later today, but xcomponent now has the fix. See https://github.com/krakenjs/cross-domain-utils/commit/40c6cb74ae5a455c23b82ad3e8536bf2059504e4
