### ISSUE TITLE
Add support to not destroy xcomponent when parent page navigates away

### ISSUE THREAD

**Issue by mmairs9** [krakenjs/xcomponent#89]
Unfortunately we are seeing some lag in our Sharepoint environment where we have an xcomponent  rendering. When navigating to a new page we receive a slow response from a server,  can we not destroy the xcomponent immediately as it disappears off view before anything else on the page?

**Comment by mmairs9** [comment]
I created a [PR](https://github.com/krakenjs/xcomponent/pull/90) for this. You may want to change the prop name.

**Comment by bluepnume** [comment]
What do you think about keeping this non-configurable, but only applying it to popups?

The reason this was added in the first place was so popup components would close on page change -- but iframe components automatically close when the page is unloaded, so seems like doing a destroy here isn't really necessary to anyone.

That or we could just make this happen on `unload` rather than `beforeunload` so the component doesn't disappear too soon?

**Comment by mmairs9** [comment]
That makes sense to me to be non configurable and to not have the logic to destroy the component if it is an iframe.

**Comment by harouny** [comment]
+1 for only apply close component on page unload when coponent is a popup.
Browsers should take care of closing the iframe.

**Comment by harouny** [comment]
On a related note, I think making this happen on '''unload''' is better than '''beforeUnload''' . I'm not sure what's the behavior if someone have this in the page that opened the popup to show a navigating away confirmation and user cancels navigation.
'''
window.onbeforeunload = function() {
    return true;
};
'"

**Comment by harouny** [comment]
sorry writing on mobile :(

**Comment by bluepnume** [comment]
Yeah it's a fair point. I think it was mainly just me not trusting `unload` enough to do everything I needed it to before the page unloads.

**Comment by bluepnume** [comment]
OK, made this change and published. Please let me know if it works ok for you. For now I've gone with the `unload` fix rather than branching the logic any further for popups vs iframes.

**Comment by figalex** [comment]
Is there currently a way to prevent a popup from being destroyed when parent is reloaded? We are trying to open a separate widget in a popup window that needs to persist while the user is navigating through different pages under our domain but as soon as the main (parent) page is reloaded or user clicks in a new link the popup is destroyed.
