### ISSUE TITLE
multiple xcomponents on a page sometimes render in wrong location

### ISSUE THREAD

**Issue by mmairs9** [krakenjs/xcomponent#91]
I have in some cases 2 xcomponents on the same page. Ive noticed that the odd time one xcomponent is rendering in place of another as if they are getting mixed up.

Ive added a delay in rendering the 2nd component to get around this issue for the time being.

**Comment by bluepnume** [comment]
Hey @mmairs9 thanks for the report -- let me try to set up a test scenario and see if I can repro.

**Comment by mmairs9** [comment]
I have have had trouble recreating it today as it happened sporadically.
Will see if I can recreate over the next few days.

**Comment by mmairs9** [comment]
The delay i put in place in creating the second component seemed to do the trick. I have not been able to reproduce since. This is probably good to close!

**Comment by bluepnume** [comment]
OK, closing. Little worried that something like what you described could happen without artificial delays, so please let me know if you ever repro consistently in future. Feels a little like a race-condition of some kind.
