### ISSUE TITLE
How can child(iframe) expose a function which the render(parent/host) can use?

### ISSUE THREAD

**Issue by abhijeetahuja** [krakenjs/xcomponent#94]
```
window.xprops.myCustomFunction  = () => {
     console.log('do something');
}
```

Then how can parent access it?

window.xcomponent.xprops.myCustomFunction  ?
or
RenderedXComponent.props.myCustomFunction  ??

**Comment by harouny** [comment]
https://github.com/krakenjs/xcomponent/blob/master/docs/example.md

**Comment by harouny** [comment]
Properties meant to communicate down (from parent to child) and functions to communicate up (from child to parent). 
A function however can accept a callback function that parent can call.

**Comment by bluepnume** [comment]
Yeah, pretty much as @harouny said. You can pass down a function, then pass another function up as a callback. There's an example here: https://github.com/krakenjs/xcomponent/issues/53

**Comment by dziamid** [comment]
What if I want to expose some API of my component for the parent to use? E.g. my widget is a phone, and client wants the api to trigger a phone call.
