### ISSUE TITLE
Ability to send HTTP headers in the URL on create

### ISSUE THREAD

**Issue by sonoman** [krakenjs/xcomponent#95]
Hi there:

Is it possible to ensure that certain http headers are added in the http request that is submitted when `xcomponent.create({ ..., url: "http://www.asdfasdfasdfasfdasf.com" }))` is called ?

**Comment by bluepnume** [comment]
Unfortunately not. The url is loaded in a popup window or an iframe, not via ajax, so there's no way to programmatically set headers.
