### ISSUE TITLE
Rendering external url inside xcomponent

### ISSUE THREAD

**Issue by BrendanJones44** [krakenjs/xcomponent#99]
I'm not sure if I'm just misunderstanding this, or it's an issue. Using xcomponent, I should be able to render an external url, like http:www.google.com, inside of an iFrame, inside my own component? I can't seem to get this working.

Details:
I'm working with a react project where I want to load other html pages on my site, without cross domain issues.

**Comment by bluepnume** [comment]
Hi @BrendanJones44. That's a negative -- if google.com blocks iframes, there's nothing xcomponent can do to allow it to work.

xcomponent is mostly useful when you're the owner of the page inside the iframe, and you want to easily expose your page it to 3rd party sites and allow them to pass props/callbacks/etc to you.

Hope that clarifies -- please let me know if I can elaborate! Thanks
